routes/web.php
<?php

use App\Models\Role;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\KarirController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\KategoriJasaController;
use App\Http\Controllers\KategoriProdukController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


// Routes Roles 
// Route::get('/role', [RoleController::class, 'index'])->middleware('auth');
Route::resource('role', RoleController::class)->middleware('auth');
Route::resource('user', UserController::class);
Route::resource('kategori-jasa', KategoriJasaController::class);
Route::resource('kategori-produk', KategoriProdukController::class);
Route::resource('karir', KarirController::class);



Route::get('/produk', function () {
    return view('master.produk.index');
});

Route::get('/login', [LoginController::class, 'view'])->name('login');

Route::post('/login/auth', [LoginController::class, 'storeLogin'])->name('postLogin')->middleware('guest');


// 
// *
// *
// *
// Route For Portal

Route::get('/home', function () {
    return view('portal.home.home');
});

app/Models/Produk.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Produk extends Model
{
    use HasFactory;

    protected $fillable = [
        'produk_kategori_id',
        'produk_nama',
        'produk_harga',
        'produk_qty',
        'produk_detail',
        'produk_is_active',
    ];

    public function kategori(){
        return $this->belongsTo(kategoriProduk::class, 'produk_kategori_id', 'id');
    }

    public function thumbs(){
        return $this->hasMany(ProdukThumb::class, 'produk_id');
    }
}

app/Http/Controllers/ProdukController.php
<?php

namespace App\Http\Controllers;

use App\Models\Produk;
use Illuminate\Http\Request;

class ProdukController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Produk  $produk
     * @return \Illuminate\Http\Response
     */
    public function show(Produk $produk)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Produk  $produk
     * @return \Illuminate\Http\Response
     */
    public function edit(Produk $produk)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Produk  $produk
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Produk $produk)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Produk  $produk
     * @return \Illuminate\Http\Response
     */
    public function destroy(Produk $produk)
    {
        //
    }
}

resources/views/master/produk/edit.blade.php
@extends('layouts.main')

@section('content')
<div class="card">
   <div class="card card-custom">
      <div class="card-header flex-wrap border-0 pt-6 pb-0">
         <div class="card-title">
            <h3 class="card-label">Form Karir
         </div>
         <div class="card-toolbar">
            <a href="{{ route('karir.index') }}" class="btn btn-sm btn-default"><i class="fas fa-angle-left"></i>Kembali</a>
         </div>
      </div>
      <form action="{{ route('karir.update',$karir->id) }}" method="POST">
         @csrf
         @method('PUT')
         <div class="card-body">
            <div class="form-group row">
               <label class="col-3 col-form-label">Nama Pekerjaan
                  <span class="text-danger">*</span>
               </label>
               <div class="col-9">
                  <input type="text" name="karir_position" id="karir_position" class="form-control" value="{{ $karir['karir_position'] }}" placeholder="Masukkan Nama" autocomplete="off" />
               </div>
            </div>
            <div class="form-group row">
               <label class="col-3 col-form-label">Detail Pekerjaan
                  <span class="text-danger">*</span>
               </label>
               <div class="col-9">
                  <textarea name="karir_detail" id="karir_detail" class="form-control" rows="3">{{ $karir['karir_detail'] }}</textarea>
               </div>
            </div>
            <div class="form-group row">
               <label class="col-3 col-form-label">Detail Pekerjaan
                  <span class="text-danger">*</span>
               </label>
               <div class="col-9">
                  <select class="form-control selectpicker" title="-- Pilih --" name="karir_type">
                     <option value="Intern" class="{{ ($karir['karir_type'] == 'Intern')?'selected-active':'' }}">Intern</option>
                     <option value="Full-time" class="{{ ($karir['karir_type'] == 'Full-time')?'selected-active':'' }}">Full-time</option>
                  </select>
               </div>
            </div>
            <div id="reqruitment">
               
               <div class="form-group row">
                  <label class="col-3 col-form-label">Persyaratan dan Kualifikasi
                     <span class="text-danger">*</span>
                  </label>
                  <div class="col-9">
                     @foreach ($req as $key => $value )
                     <div class="input-group mb-1">
                        <input type="text" class="form-control" name="reqruitment_detail[{{ $key }}]" placeholder="Masukkan Syarat" autocomplete="off" value="{{ $value['reqruitment_detail'] }}"/>
                     </div>
                     @endforeach
                     <div id="form-repeater-req"></div>
                  </div>
               </div>
               <div class="form-group row mt-0">
                  <div class="col-lg-3"></div>
                     <div class="col">
                           <a data-repeater-create="" onclick="addReqruitment(this)" class="btn font-weight-bold btn-info btn-sm">
                              <i class="la la-plus text-center"></i>
                              Tambah
                           </a>
                           <a onclick="removeReqruitment(this)" class="btn font-weight-bold btn-sm btn-danger btn-icon">
                              <i class="la la-close"></i>
                           </a>
                     </div>
               </div>
            </div>
            <div id="task">
               <div class="form-group row">
                  <label class="col-3 col-form-label">Tugas dan Kewajiban
                     <span class="text-danger">*</span>
                  </label>
                  <div class="col-9">
                     @foreach ($task as $key => $value )
                     <div class="input-group mb-1">
                        <input type="text" class="form-control" name="task_detail[{{ $key }}]" placeholder="Masukkan Tugas" autocomplete="off" value="{{ $value['task_detail'] }}"/>
                     </div>
                     @endforeach
                     <div id="form-repeater-task"></div>
                  </div>
               </div>
               <div class="form-group row mt-0">
                  <div class="col-lg-3"></div>
                     <div class="col">
                           <a data-repeater-create="" onclick="addTask(this)" class="btn font-weight-bold btn-info btn-sm">
                              <i class="la la-plus"></i>
                              Tambah
                           </a>
                           <a onclick="removeTask(this)" class="btn font-weight-bold btn-sm btn-danger btn-icon">
                              <i class="la la-close"></i>
                           </a>
                     </div>
               </div>
            </div>
            {{-- <div class="form-group row">
               <label class="col-3 col-form-label">Status</label>
               <div class="col-3">
                  <span class="switch switch-success">
                     <label>
                        <input type="checkbox" checked="checked" name="karir_is_active" />
                        <span></span>
                     </label>
                  </span>
               </div>
            </div> --}}
            <div class="card-footer p-0 text-right pt-3">
               <button type="reset" class="btn btn-sm btn-light-success font-weight-bold"><i class="fas fa-undo-alt"></i> Batal</button>
               <button type="submit" class="btn btn-sm btn-success font-weight-bold mr-2"><i class="far fa-save"></i> Simpan</button>
            </div>
      </form>
   </div>
</div>
@endsection

@section('javascript')

<script>
   var id = 0;
   var idTask = 0;
   function addReqruitment(el){
      id++;
      $('#form-repeater-req').append(`
         <div class="input-group mb-3" id="reqruitment_detail${id}">
            <input type="text" class="form-control" name="reqruitment_detail[${id}]" autocomplete="off" placeholder="Masukkan Syarat"/>
         </div>
      `);
   }
   
   function removeReqruitment(el){
      $(`#reqruitment_detail${id}`).remove();
      id--;
   }

   function addTask(el){
      idTask++;
      $('#form-repeater-task').append(`
         <div class="input-group mb-3" id="task_detail${idTask}">
            <input type="text" class="form-control" name="task_detail[${idTask}]" autocomplete="off" placeholder="Masukkan Tugas"/>
         </div>
      `);
   }
   
   function removeTask(el){
      $(`#task_detail${idTask}`).remove();
      idTask--;
   }
</script>

@endsection

resources/views/master/produk/index.blade.php
@extends('layouts.main')

@section('content')
<div class="card card-custom card-stretch gutter-b">
   <div class="card-body">
      <!--begin::Engage Widget 15-->
      <div class="card card-custom mb-12">
         <div class="card-body rounded p-0 d-flex" style="background-color:#DAF0FD;">
            <div class="d-flex flex-column flex-lg-row-auto w-auto w-lg-350px w-xl-450px w-xxl-500px p-10 p-md-20">
               <h1 class="font-weight-bolder text-dark">Search Products</h1>
               <div class="font-size-h4 mb-8">Get All Products</div>
               <!--begin::Form-->
               <form class="d-flex flex-center py-2 px-6 bg-white rounded">
                  <span class="svg-icon svg-icon-lg svg-icon-primary">
                     <!--begin::Svg Icon | path:assets/media/svg/icons/General/Search.svg-->
                     <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1">
                        <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                           <rect x="0" y="0" width="24" height="24" />
                           <path d="M14.2928932,16.7071068 C13.9023689,16.3165825 13.9023689,15.6834175 14.2928932,15.2928932 C14.6834175,14.9023689 15.3165825,14.9023689 15.7071068,15.2928932 L19.7071068,19.2928932 C20.0976311,19.6834175 20.0976311,20.3165825 19.7071068,20.7071068 C19.3165825,21.0976311 18.6834175,21.0976311 18.2928932,20.7071068 L14.2928932,16.7071068 Z" fill="#000000" fill-rule="nonzero" opacity="0.3" />
                           <path d="M11,16 C13.7614237,16 16,13.7614237 16,11 C16,8.23857625 13.7614237,6 11,6 C8.23857625,6 6,8.23857625 6,11 C6,13.7614237 8.23857625,16 11,16 Z M11,18 C7.13400675,18 4,14.8659932 4,11 C4,7.13400675 7.13400675,4 11,4 C14.8659932,4 18,7.13400675 18,11 C18,14.8659932 14.8659932,18 11,18 Z" fill="#000000" fill-rule="nonzero" />
                        </g>
                     </svg>
                     <!--end::Svg Icon-->
                  </span>
                  <input type="text" class="form-control border-0 font-weight-bold pl-2" placeholder="Search Goods" />
               </form>
               <!--end::Form-->
            </div>
            <div class="d-none d-md-flex flex-row-fluid bgi-no-repeat bgi-position-y-center bgi-position-x-left bgi-size-cover" style="background-image: url(assets/media/svg/illustrations/progress.svg);"></div>
         </div>
      </div>
      <!--end::Engage Widget 15-->
      <!--begin::Section-->
      <div class="mb-11">
         <!--begin::Heading-->
         <div class="d-flex justify-content-between align-items-center mb-7">
               <a href="" class="btn btn-light-success btn-sm font-weight-bolder">
               <span class="svg-icon svg-icon-succcess svg-icon-2x">
                  <!--begin::Svg Icon | path:C:\wamp64\www\keenthemes\themes\metronic\theme\html\demo1\dist/../src/media/svg/icons\Code\Plus.svg--><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1">
                     <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                        <rect x="0" y="0" width="24" height="24" />
                        <circle fill="#000000" opacity="0.3" cx="12" cy="12" r="10" />
                        <path d="M11,11 L11,7 C11,6.44771525 11.4477153,6 12,6 C12.5522847,6 13,6.44771525 13,7 L13,11 L17,11 C17.5522847,11 18,11.4477153 18,12 C18,12.5522847 17.5522847,13 17,13 L13,13 L13,17 C13,17.5522847 12.5522847,18 12,18 C11.4477153,18 11,17.5522847 11,17 L11,13 L7,13 C6.44771525,13 6,12.5522847 6,12 C6,11.4477153 6.44771525,11 7,11 L11,11 Z" fill="#000000" />
                     </g>
                  </svg>
                  <!--end::Svg Icon-->
               </span>Tambah</a>
         </div>
         <!--end::Heading-->
         <!--begin::Products-->
         <div class="row">
            <!--begin::Product-->
            <div class="col-md-4 col-xxl-4">
               <!--begin::Card-->
               <div class="card card-custom card-shadowless">
                  <div class="card-body p-0">
                     <!--begin::Image-->
                     <div class="overlay">
                        <div class="overlay-wrapper rounded bg-light text-center">
                           <img src="assets/media/products/1.png" alt="" class="mw-100 w-200px" />
                        </div>
                        <div class="overlay-layer">
                           <a href="#" class="btn font-weight-bolder btn-sm btn-primary mr-2">Quick View</a>
                           <a href="#" class="btn font-weight-bolder btn-sm btn-danger mr-2">Delete Photo</a>
                        </div>
                     </div>
                     <!--end::Image-->
                     <!--begin::Details-->
                     <div class="text-center mt-5 mb-md-0 mb-lg-5 mb-md-0 mb-lg-5 mb-lg-0 mb-5 d-flex flex-column">
                        <a href="#" class="font-size-h5 font-weight-bolder text-dark-75 text-hover-primary mb-1">Smart Watches</a>
                        <span class="font-size-lg">Outlines keep poorly thought</span>
                     </div>
                     <!--end::Details-->
                  </div>
               </div>
               <!--end::Card-->
            </div>
            <!--end::Product-->
            <!--begin::Product-->
            <div class="col-md-4 col-xxl-4">
               <!--begin::Card-->
               <div class="card card-custom card-shadowless">
                  <div class="card-body p-0">
                     <!--begin::Image-->
                     <div class="overlay">
                        <div class="overlay-wrapper rounded bg-light text-center">
                           <img src="assets/media/products/2.png" alt="" class="mw-100 w-200px" />
                        </div>
                        <div class="overlay-layer">
                           <a href="#" class="btn font-weight-bolder btn-sm btn-primary mr-2">Quick View</a>
                           <a href="#" class="btn font-weight-bolder btn-sm btn-danger mr-2">Delete Photo</a>
                        </div>
                     </div>
                     <!--end::Image-->
                      <!--begin::Details-->
                     <div class="text-center mt-5 mb-md-0 mb-lg-5 mb-md-0 mb-lg-5 mb-lg-0 mb-5 d-flex flex-column">
                        <a href="#" class="font-size-h5 font-weight-bolder text-dark-75 text-hover-primary mb-1">Smart Watches</a>
                        <span class="font-size-lg">Outlines keep poorly thought</span>
                     </div>
                     <!--end::Details-->
                  </div>
               </div>
               <!--end::Card-->
            </div>
            <!--end::Product-->
            <!--begin::Product-->
            <div class="col-md-4 col-xxl-4">
               <!--begin::Card-->
               <div class="card card-custom card-shadowless">
                  <div class="card-body p-0">
                     <!--begin::Image-->
                     <div class="overlay">
                        <div class="overlay-wrapper rounded bg-light text-center">
                           <img src="assets/media/products/3.png" alt="" class="mw-100 w-200px" />
                        </div>
                        <div class="overlay-layer">
                           <a href="#" class="btn font-weight-bolder btn-sm btn-primary mr-2">Quick View</a>
                           <a href="#" class="btn font-weight-bolder btn-sm btn-danger mr-2">Delete Photo</a>
                        </div>
                     </div>
                     <!--end::Image-->
                      <!--begin::Details-->
                     <div class="text-center mt-5 mb-md-0 mb-lg-5 mb-md-0 mb-lg-5 mb-lg-0 mb-5 d-flex flex-column">
                        <a href="#" class="font-size-h5 font-weight-bolder text-dark-75 text-hover-primary mb-1">Smart Watches</a>
                        <span class="font-size-lg">Outlines keep poorly thought</span>
                     </div>
                     <!--end::Details-->
                  </div>
               </div>
               <!--end::Card-->
            </div>
            <!--end::Product-->
         </div>
         <!--end::Products-->
      </div>
      <!--end::Section-->
   </div>
</div>
@endsection

resources/views/master/produk/tambah.blade.php
@extends('layouts.main')

@section('content')
<div class="card">
   <div class="card card-custom">
      <div class="card-header flex-wrap border-0 pt-6 pb-0">
         <div class="card-title">
            <h3 class="card-label">Form Karir
         </div>
         <div class="card-toolbar">
            <a href="{{ route('karir.index') }}" class="btn btn-sm btn-default"><i class="fas fa-angle-left"></i>Kembali</a>
         </div>
      </div>
      <form action="{{ route('karir.store') }}" method="POST">
         @csrf
         <div class="card-body">
            <div class="form-group row">
               <label class="col-3 col-form-label">Nama Pekerjaan
                  <span class="text-danger">*</span>
               </label>
               <div class="col-9">
                  <input type="text" name="karir_position" id="karir_position" class="form-control" placeholder="Masukkan Nama" autocomplete="off" />
               </div>
            </div>
            <div class="form-group row">
               <label class="col-3 col-form-label">Detail Pekerjaan
                  <span class="text-danger">*</span>
               </label>
               <div class="col-9">
                  <textarea name="karir_detail" id="karir_detail" class="form-control" rows="3"></textarea>
               </div>
            </div>
            <div class="form-group row">
               <label class="col-3 col-form-label">Detail Pekerjaan
                  <span class="text-danger">*</span>
               </label>
               <div class="col-9">
                  <select class="form-control selectpicker" title="-- Pilih --" name="karir_type">
                     <option value="Intern">Intern</option>
                     <option value="Full-time">Full-time</option>
                  </select>
               </div>
            </div>
            <div id="reqruitment">
               <div class="form-group row">
                  <label class="col-3 col-form-label">Persyaratan dan Kualifikasi
                     <span class="text-danger">*</span>
                  </label>
                  <div class="col-9">
                     <div class="input-group mb-1">
                        <input type="text" class="form-control" name="reqruitment_detail[0]" placeholder="Masukkan Syarat" autocomplete="off"/>
                     </div>
                     <div id="form-repeater-req"></div>
                  </div>
               </div>
               <div class="form-group row mt-0">
                  <div class="col-lg-3"></div>
                     <div class="col">
                           <a data-repeater-create="" onclick="addReqruitment(this)" class="btn font-weight-bold btn-info btn-sm">
                              <i class="la la-plus text-center"></i>
                              Tambah
                           </a>
                           <a onclick="removeReqruitment(this)" class="btn font-weight-bold btn-sm btn-danger btn-icon">
                              <i class="la la-close"></i>
                           </a>
                     </div>
               </div>
            </div>
            <div id="task">
               <div class="form-group row">
                  <label class="col-3 col-form-label">Tugas dan Kewajiban
                     <span class="text-danger">*</span>
                  </label>
                  <div class="col-9">
                     <div class="input-group mb-1">
                        <input type="text" class="form-control" name="task_detail[0]" placeholder="Masukkan Tugas" autocomplete="off"/>
                     </div>
                     <div id="form-repeater-task"></div>
                  </div>
               </div>
               <div class="form-group row mt-0">
                  <div class="col-lg-3"></div>
                     <div class="col">
                           <a data-repeater-create="" onclick="addTask(this)" class="btn font-weight-bold btn-info btn-sm">
                              <i class="la la-plus"></i>
                              Tambah
                           </a>
                           <a onclick="removeTask(this)" class="btn font-weight-bold btn-sm btn-danger btn-icon">
                              <i class="la la-close"></i>
                           </a>
                     </div>
               </div>
            </div>
            {{-- <div class="form-group row">
               <label class="col-3 col-form-label">Status</label>
               <div class="col-3">
                  <span class="switch switch-success">
                     <label>
                        <input type="checkbox" checked="checked" name="karir_is_active" />
                        <span></span>
                     </label>
                  </span>
               </div>
            </div> --}}
            <div class="card-footer p-0 text-right pt-3">
               <button type="reset" class="btn btn-sm btn-light-success font-weight-bold"><i class="fas fa-undo-alt"></i> Batal</button>
               <button type="submit" class="btn btn-sm btn-success font-weight-bold mr-2"><i class="far fa-save"></i> Simpan</button>
            </div>
      </form>
   </div>
</div>
@endsection

@section('javascript')

<script>
   var id = 0;
   var idTask = 0;
   function addReqruitment(el){
      id++;
      $('#form-repeater-req').append(`
         <div class="input-group mb-3" id="reqruitment_detail${id}">
            <input type="text" class="form-control" name="reqruitment_detail[${id}]" autocomplete="off" placeholder="Masukkan Syarat"/>
         </div>
      `);
   }
   
   function removeReqruitment(el){
      $(`#reqruitment_detail${id}`).remove();
      id--;
   }

   function addTask(el){
      idTask++;
      $('#form-repeater-task').append(`
         <div class="input-group mb-3" id="task_detail${idTask}">
            <input type="text" class="form-control" name="task_detail[${idTask}]" autocomplete="off" placeholder="Masukkan Tugas"/>
         </div>
      `);
   }
   
   function removeTask(el){
      $(`#task_detail${idTask}`).remove();
      idTask--;
   }
</script>

@endsection