routes/web.php
<?php

use App\Models\Role;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\KarirController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\KategoriJasaController;
use App\Http\Controllers\KategoriProdukController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


// Routes Roles 
// Route::get('/role', [RoleController::class, 'index'])->middleware('auth');
Route::resource('role', RoleController::class)->middleware('auth');
Route::resource('user', UserController::class);
Route::resource('kategori-jasa', KategoriJasaController::class);
Route::resource('kategori-produk', KategoriProdukController::class);
Route::resource('karir', KarirController::class);



Route::get('/produk', function () {
    return view('master.produk.index');
});

Route::get('/login', [LoginController::class, 'view'])->name('login');

Route::post('/login/auth', [LoginController::class, 'storeLogin'])->name('postLogin')->middleware('guest');


// 
// *
// *
// *
// Route For Portal

Route::get('/home', function () {
    return view('portal.home.home');
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'user_name',
        'user_email',
        'user_username',
        'user_password',
        'user_is_active',
        'user_telp',
        'user_alamat',
        'user_photo',
        'user_role_id',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'user_password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'user_verified_at' => 'datetime',
    ];

    public function roles(){
        return $this->belongsTo(Role::class, 'user_role_id', 'id');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\Role;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Validator;
// use App\Http\Requests\StoreUserRequest;



class UserController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::with('roles')->latest()->get();
        // dd($users);
        
        return view('master.user.user', compact('users'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $users = new User;
        $roles = Role::all();
        return view('master.user.form', compact(
            'users',
            'roles'
        ));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // Validator Form
        $validator = Validator::make($request->all(), [
            'user_photo'     => 'required|file|image|mimes:jpeg,png,jpg,svg|max:2048',
            'user_username'    => 'required',
            'user_email'    => 'required',
            'user_password'   => 'required',
            'user_telp'   => 'required|min:11',
            'user_alamat'   => 'required',
            'user_role_id'   => 'required',
        ]);
        
        if ($validator->fails()) {
            return redirect()->route('user.create')
            ->with('failed', 'User Create Not Success');
        }

        // upload image
        $file = $request->file('user_photo');
        $file_name = $file->hashName();
        $file_path = storage_path('app/public/uploads/users');
        $file->move($file_path, $file_name);
    
        //create user
        User::create([
            'user_photo'     => $file_name,
            'user_name' => $request['user_name'],
            'user_username' => $request['user_username'],
            'user_email' => $request['user_email'],
            'user_password' => Hash::make($request['user_password']),
            'user_telp' => $request['user_telp'],
            'user_alamat' => $request['user_alamat'],
            'user_role_id' => $request['user_role_id'],
        ]);

        return redirect()->route('user.index')
            ->with('success', 'User Created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        $users = User::find($user);
        $roles = Role::all();
        return view('master.user.edit', compact('user','roles'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $user)
    {
        // Validator Form
        $validator = Validator::make($request->all(), [
            'user_photo'     => 'required|file|image|mimes:jpeg,png,jpg,svg|max:2048',
        ]);

        if ($validator->fails()) {
            return redirect()->route('user.create')
            ->with('failed', 'User Update Not Success');
        }

        $users = User::find($user);

        //check if image is uploaded
        if ($request->hasFile('user_photo')){
            
             //upload new image
            $file = $request->file('user_photo');
            $file_name = $file->hashName();
            $file_path = storage_path('app/public/uploads/users');
            $file->move($file_path, $file_name);

            //delete old image
            Storage::delete('public/uploads/users/'.$file_name);

            //Update user
            $users->update([
                'user_photo'     => $file_name,
                'user_name' => $request['user_name'],
                'user_username' => $request['user_username'],
                'user_telp' => $request['user_telp'],
                'user_alamat' => $request['user_alamat'],
                'user_role_id' => $request['user_role_id'],
            ]);

        }else{
            //Update user
             $users->update([
                'user_name' => $request['user_name'],
                'user_username' => $request['user_username'],
                'user_telp' => $request['user_telp'],
                'user_alamat' => $request['user_alamat'],
                'user_role_id' => $request['user_role_id'],
            ]);

        }

        //  return to redirect
         return redirect()->route('user.index')
                ->with('success', 'User Created successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        //delete image
        Storage::delete('public/uploads/users/'. $user->user_photo);

        //delete post
        $user->delete();

        //redirect to index
        return redirect()->route('user.index')->with(['success' => 'Data Berhasil Dihapus!']);
    }
}

resources/views/master/user/edit.blade.php
@extends('layouts.main')

@section('content')
<div class="card mb-3">
   <div class="card card-custom">
      <div class="card-header flex-wrap border-0 pt-6 pb-0">
         <div class="card-title">
            <h3 class="card-label">Form User
         </div>
         <div class="card-toolbar">
            <a href="{{ route('user.index') }}" class="btn btn-sm btn-default"><i class="fas fa-angle-left"></i>Kembali</a>
         </div>
      </div>
      <form action="{{ route('user.update',$user->id) }}" method="POST" enctype="multipart/form-data">
         @csrf
         @method('PUT')
         <div class="card-body">
            <div class="row">
               <div class="col-md-6">
                  <div class="form-group row">
                     <label class="col-md-3 col-form-label">Nama
                        <span class="text-danger">*</span>
                     </label>
                     <div class="col-md-9">
                        <input type="text" name="user_name" id="user_name" class="form-control" value="{{ $user->user_name }}" placeholder="Masukkan Nama" autocomplete="off" />
                     </div>
                  </div>
                  <div class="form-group row">
                     <label class="col-md-3 col-form-label">Role
                        <span class="text-danger">*</span>
                     </label>
                     <div class="col-md-9">
                        <select class="form-control selectpicker" title="{{ optional($user->roles)->role_nama }}" name="user_role_id">
                           @foreach ( $roles as $value )
                               <option value="{{ $value->id }}">{{ $value->role_nama }}</option>
                           @endforeach
                        </select>
                     </div>
                  </div>
                  <div class="form-group row">
                     <label class="col-md-3 col-form-label">Nomer Telp
                        <span class="text-danger">*</span>
                     </label>
                     <div class="col-md-9">
                        <input type="text" name="user_telp" id="user_telp" class="form-control" value="{{ $user->user_telp }}" placeholder="Masukkan Telp" autocomplete="off" />
                     </div>
                  </div>
                  <div class="form-group row">
                     <label class="col-md-3 col-form-label">Alamat
                        <span class="text-danger">*</span>
                     </label>
                     <div class="col-md-9">
                        <textarea name="user_alamat" id="user_alamat" class="form-control" rows="3">{{ $user->user_alamat }}</textarea>
                     </div>
                  </div>        
                  <div class="form-group row">
                     <label class="col-3 col-form-label">Status</label>
                     <div class="col-9">
                        <span class="switch switch-success">
                           <label>
                              <input type="checkbox" checked="checked" name="user_is_active" />
                              <span></span>
                           </label>
                        </span>
                     </div>
                  </div>                   
               </div>
               <div class="col-md-6">
                  <div class="form-group row">
                     <label class="col-md-3 col-form-label">Email
                        <span class="text-danger">*</span>
                     </label>
                     <div class="col-md-9">
                        <input type="text" name="user_email" id="user_email" class="form-control" value="{{ $user->user_email }}" placeholder="Masukkan Email" autocomplete="off" />
                     </div>
                  </div>
                  <div class="form-group row">
                     <label class="col-md-3 col-form-label">Username
                        <span class="text-danger">*</span>
                     </label>
                     <div class="col-md-9">
                        <input type="text" name="user_username" id="user_username" class="form-control" value="{{ $user->user_username }}" placeholder="Masukkan Username" autocomplete="off" />
                     </div>
                  </div>
                  <div class="form-group row">
                     <label class="col-md-3 col-form-label">Password
                        <span class="text-danger">*</span>
                     </label>
                     <div class="col-md-9">
                        <input type="password" name="user_password" id="user_password" class="form-control" value="{{ $user->user_password }}" placeholder="Masukkan Password" autocomplete="off" />
                     </div>
                  </div>
                  <div class="form-group row">
                     <label class="col-3 col-form-label">Foto
                        <span class="text-danger">*</span>
                     </label>
                     <div class="col-9">
                        <div class="image-input image-input-empty image-input-outline" id="kt_image_5" style="background-image: url(storage/uploads/users/{{ $user->user_photo }})">
                        <div class="image-input-wrapper"></div>

                        <label class="btn btn-xs btn-icon btn-circle btn-white btn-hover-text-primary btn-shadow" data-action="change" data-toggle="tooltip" title="" data-original-title="Change avatar">
                        <i class="fa fa-pen icon-sm text-muted"></i>
                        <input type="file" name="user_photo" accept=".png, .jpg, .jpeg"/>
                        <input type="hidden" name="user_photo_remove"/>
                        </label>

                        <span class="btn btn-xs btn-icon btn-circle btn-white btn-hover-text-primary btn-shadow" data-action="cancel" data-toggle="tooltip" title="Cancel avatar">
                        <i class="ki ki-bold-close icon-xs text-muted"></i>
                        </span>

                        <span class="btn btn-xs btn-icon btn-circle btn-white btn-hover-text-primary btn-shadow" data-action="remove" data-toggle="tooltip" title="Remove avatar">
                        <i class="ki ki-bold-close icon-xs text-muted"></i>
                        </span>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         <div class="card-footer text-right pt-3">
            <button type="reset" class="btn btn-sm btn-light-success font-weight-bold"><i class="fas fa-undo-alt"></i> Batal</button>
            <button type="submit" class="btn btn-sm btn-success font-weight-bold mr-2"><i class="far fa-save"></i> Simpan</button>
         </div>
      </form>
   </div>
</div>
@endsection

resources/views/master/user/form.blade.php
@extends('layouts.main')

@section('content')
<div class="card mb-3">
   <div class="card card-custom">
      <div class="card-header flex-wrap border-0 pt-6 pb-0">
         <div class="card-title">
            <h3 class="card-label">Form User
         </div>
         <div class="card-toolbar">
            <a href="{{ route('user.index') }}" class="btn btn-sm btn-default"><i class="fas fa-angle-left"></i>Kembali</a>
         </div>
      </div>
      <form action="{{ route('user.store') }}" method="POST" enctype="multipart/form-data">
         @csrf
         <div class="card-body">
            <div class="row">
               <div class="col-md-6">
                  <div class="form-group row">
                     <label class="col-md-3 col-form-label">Nama
                        <span class="text-danger">*</span>
                     </label>
                     <div class="col-md-9">
                        <input type="text" name="user_name" id="user_name" class="form-control" placeholder="Masukkan Nama" autocomplete="off" />
                     </div>
                  </div>
                  <div class="form-group row">
                     <label class="col-md-3 col-form-label">Role
                        <span class="text-danger">*</span>
                     </label>
                     <div class="col-md-9">
                        <select class="form-control selectpicker" title="-- Pilih --" name="user_role_id">
                           @foreach ( $roles as $value )
                               <option value="{{ $value->id }}">{{ $value->role_nama }}</option>
                           @endforeach
                        </select>
                     </div>
                  </div>
                  <div class="form-group row">
                     <label class="col-md-3 col-form-label">Nomer Telp
                        <span class="text-danger">*</span>
                     </label>
                     <div class="col-md-9">
                        <input type="text" name="user_telp" id="user_telp" class="form-control" placeholder="Masukkan Telp" autocomplete="off" />
                     </div>
                  </div>
                  <div class="form-group row">
                     <label class="col-md-3 col-form-label">Alamat
                        <span class="text-danger">*</span>
                     </label>
                     <div class="col-md-9">
                        <textarea name="user_alamat" id="user_alamat" class="form-control" rows="3"></textarea>
                     </div>
                  </div>        
                  <div class="form-group row">
                     <label class="col-3 col-form-label">Status</label>
                     <div class="col-9">
                        <span class="switch switch-success">
                           <label>
                              <input type="checkbox" checked="checked" name="user_is_active" />
                              <span></span>
                           </label>
                        </span>
                     </div>
                  </div>                   
               </div>
               <div class="col-md-6">
                  <div class="form-group row">
                     <label class="col-md-3 col-form-label">Email
                        <span class="text-danger">*</span>
                     </label>
                     <div class="col-md-9">
                        <input type="text" name="user_email" id="user_email" class="form-control" placeholder="Masukkan Email" autocomplete="off" />
                     </div>
                  </div>
                  <div class="form-group row">
                     <label class="col-md-3 col-form-label">Username
                        <span class="text-danger">*</span>
                     </label>
                     <div class="col-md-9">
                        <input type="text" name="user_username" id="user_username" class="form-control" placeholder="Masukkan Username" autocomplete="off" />
                     </div>
                  </div>
                  <div class="form-group row">
                     <label class="col-md-3 col-form-label">Password
                        <span class="text-danger">*</span>
                     </label>
                     <div class="col-md-9">
                        <input type="password" name="user_password" id="user_password" class="form-control" placeholder="Masukkan Password" autocomplete="off" />
                     </div>
                  </div>
                  {{-- <div class="form-group row">
                     <label class="col-md-3 col-form-label">Foto
                        <span class="text-danger">*</span>
                     </label>
                     <div class="col-md-9">
                        <input class="form-control form-control-sm" id="user_photo" name="user_photo" type="file">
                     </div>
                  </div> --}}
                  <div class="form-group row">
                     <label class="col-3 col-form-label">Foto
                        <span class="text-danger">*</span>
                     </label>
                     <div class="col-9">
                        <div class="image-input image-input-empty image-input-outline" id="kt_image_5" style="background-image: url(assets/media/users/blank.png)">
                        <div class="image-input-wrapper"></div>

                        <label class="btn btn-xs btn-icon btn-circle btn-white btn-hover-text-primary btn-shadow" data-action="change" data-toggle="tooltip" title="" data-original-title="Change avatar">
                        <i class="fa fa-pen icon-sm text-muted"></i>
                        <input type="file" name="user_photo" accept=".png, .jpg, .jpeg"/>
                        <input type="hidden" name="user_photo_remove"/>
                        </label>

                        <span class="btn btn-xs btn-icon btn-circle btn-white btn-hover-text-primary btn-shadow" data-action="cancel" data-toggle="tooltip" title="Cancel avatar">
                        <i class="ki ki-bold-close icon-xs text-muted"></i>
                        </span>

                        <span class="btn btn-xs btn-icon btn-circle btn-white btn-hover-text-primary btn-shadow" data-action="remove" data-toggle="tooltip" title="Remove avatar">
                        <i class="ki ki-bold-close icon-xs text-muted"></i>
                        </span>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         <div class="card-footer text-right pt-3">
            <button type="reset" class="btn btn-sm btn-light-success font-weight-bold"><i class="fas fa-undo-alt"></i> Batal</button>
            <button type="submit" class="btn btn-sm btn-success font-weight-bold mr-2"><i class="far fa-save"></i> Simpan</button>
         </div>
      </form>
   </div>
</div>

{{-- <script>
   var avatar5 = new KTImageInput('kt_image_5');

avatar5.on('cancel', function(imageInput) {
 swal.fire({
  title: 'Image successfully changed !',
  type: 'success',
  buttonsStyling: false,
  confirmButtonText: 'Awesome!',
  confirmButtonClass: 'btn btn-primary font-weight-bold'
 });
});

avatar5.on('change', function(imageInput) {
 swal.fire({
  title: 'Image successfully changed !',
  type: 'success',
  buttonsStyling: false,
  confirmButtonText: 'Awesome!',
  confirmButtonClass: 'btn btn-primary font-weight-bold'
 });
});

avatar5.on('remove', function(imageInput) {
 swal.fire({
  title: 'Image successfully removed !',
  type: 'error',
  buttonsStyling: false,
  confirmButtonText: 'Got it!',
  confirmButtonClass: 'btn btn-primary font-weight-bold'
 });
});
</script> --}}
@endsection